### ISSUE TITLE
[Suggestion] Use Code Shaper as the underlying scaffolding tool

### ISSUE THREAD

**Issue by nareshbhatia** [AndrejJurkin/create-tw#11]
Have you thought of using [Code Shaper](https://www.code-shaper.dev/) as the underlying scaffolding tool. We would love to hear if it works for your use case or if there are any gaps to fill. We have also documented [how to create a custom branded CLI](https://www.code-shaper.dev/docs/how-to-guides/creating-a-custom-cli) such as `create-tw`.

**Comment by AndrejJurkin** [comment]
Thank you for the input!

We don't have a use case where we can use Code Shaper at the moment.
