### ISSUE TITLE
[Suggestion] Add An Option To Install A Tailwind UI Library, Such As DaisyUI, In The Project. 

### ISSUE THREAD

**Issue by Coding-Hashira** [AndrejJurkin/create-tw#15]
You can add an option to install any one (or probably more than one) component library based on TailwindCSS, like DaisyUI or HeadlessUI in the project.

**Comment by AndrejJurkin** [comment]
Headless UI is not framework agnostic. So that is a no-go.

But we can include Daisy UI in a plugin section.

Thanks for the suggestion
