### ISSUE TITLE
Not Working with SvelteKit

### ISSUE THREAD

**Issue by abushahmaa** [AndrejJurkin/create-tw#16]
When i try to install i found this error
![Screenshot from 2022-08-13 22-21-52](https://user-images.githubusercontent.com/72514035/184503498-daad1186-2410-421c-9bb0-90a1ccec8272.png)

**Comment by AndrejJurkin** [comment]
The error message is not related to create-tw. it seems.

 The underlying create-svelte package requires you to run node >= 16.9 and your actual version is 14.19
