### ISSUE TITLE
[Feature] Add Daisy UI integration

### ISSUE THREAD

**Issue by AndrejJurkin** [AndrejJurkin/create-tw#17]

**Comment by maciejadamski89** [comment]
Maybe good idea will be to add more UI integrations like Chakra, Meraki, Material, Preline ?

**Comment by AndrejJurkin** [comment]
Yeah, we can add integrations for Tailwind CSS plugins. But anything else that is not framework agnostic or not a plugin for Tailwind CSS would be out of the scope of this project I think.

**Comment by AndrejJurkin** [comment]
Daisy UI has been added to the plugins list in 0.0.21
