### ISSUE TITLE
Update `README.md` with some images or gif.

### ISSUE THREAD

**Issue by utkarsh1311** [AndrejJurkin/create-tw#2]
The README can be improved by adding some images of the package in action. 
This will help the users to understand how the package works and how to interact with it. 

Something like this: 

![start](https://user-images.githubusercontent.com/70108561/181296961-f5d4432b-9770-4794-b68a-01118653f045.png)
![end](https://user-images.githubusercontent.com/70108561/181297136-5c784f07-941c-4abc-8ffe-aa3fcfd012a9.png)

I think a gif showing the whole process will be a better choice.

**Comment by AndrejJurkin** [comment]
Yup, thanks for the suggestions. Definitely going to update the readme file, but first need to get some other basic things sorted out

**Comment by utkarsh1311** [comment]
Sure :+1:
