### ISSUE TITLE
Add simple integration tests

### ISSUE THREAD

**Issue by AndrejJurkin** [AndrejJurkin/create-tw#7]
It would be cool if someone could write basic integration tests to confirm that each variant creates as expected and the build is not crashing.

**Comment by ganeshpatil386386** [comment]
Hey,
@AndrejJurkin would you explain what exactly you want with a particular example?
so I can start working to write integration tests!

**Comment by AndrejJurkin** [comment]
> Hey, @AndrejJurkin would you explain what exactly you want with a particular example? so I can start working to write integration tests!

Hey, thanks for the interest. It is not assigned to anyone right now, but actually there's someone else looking into that.

He will write some basic integration tests and after we've merged it I can let you know how we can add some more if you're still interested.

**Comment by ganeshpatil386386** [comment]
Yes!
Let me know once after writing basic integration tests!
so I can start contributing!
